---
title: "R Notebook"
output: html_notebook
---

```{r}
home_location <- Sys.getenv("HOME")
credentials_location <- paste0(home_location, "/credentials.R")
source(credentials_location)
```

```{r}
library(RPostgreSQL)
```

** 1.1 Local PostgreSQL connection **

```{r}
my_db_connection <- dbConnect(drv = PostgreSQL(max.con = 2), user = postgresql_username, password = postgresql_password, dbname = 'wrestling', host = 'localhost')
```

```{r}
dbListTables(conn = my_db_connection)
```

```{r}
dbListFields(conn = my_db_connection, name = "wrestlers")
```

```{r}
data <- dbGetQuery(conn = my_db_connection, statement = "SELECT * FROM wrestlers")
data
```

column data types:

id = int
born = chr
name = chr
gender = chr
win_percent = dbl
total matches = int

** 1.2 Remote PostgreSQL connection **

```{r}
db_connect <- dbConnect(drv = PostgreSQL(max.con = 2), user = remote_elephantsql_username, password = remote_elephantsql_password, dbname = 'mvhbdgdk', host = '34.245.37.126')
```

```{r}
dbListTables(conn = db_connect)
```

```{r}
dbListFields(conn = db_connect, name = "wrestlers")
```

```{r}
data <- dbGetQuery(conn = db_connect, statement = "SELECT * FROM wrestlers")
data
```

```{r}
dbDisconnect(conn = my_db_connection)
```

```{r}
dbDisconnect(conn = db_connect)
```

