---
title: "R Notebook"
output: html_notebook
---

Basic Function

```{r}
multiply_number_by_15_then_add_4 <- function(x){
  print((x * 15) + 4)
}
```

if else Function

```{r}
return_bird_or_not_bird <- function(bird){
  if(bird == "goose" | bird == "duck" | bird == "pigeon"){
    return("bird")
  } else {
    return("not bird")
  }
}
```

case_when

```{r}
sizes <- c(13, 15, 10, 8, 22)

case_when(
  sizes > 10 ~ "Big",
  sizes <= 10 ~ "Small"
)
```

```{r}
wife_age <- c(29L, 30L, 36L, 31L, 22L)
husband_age <- c(28L, 35L, 32L, 31L, 29L)

case_when(
  wife_age > husband_age ~ "Wife older",
  husband_age > wife_age ~ "Husband older",
  wife_age == husband_age ~ "Same age"
)
```

recode

```{r}
fruit <- c("apple", "apple", "banana", "cherry", "cherry")

recode(fruit, "apple" = "alpaca", "banana" = "bonobo", "cherry" = "chipmunk")
```

for Loops

```{r}
my_list <- list(
  4,
  "apple",
  10.5,
  c("is", "an", "apple"),
  "apple",
  c("i", "like", "apples"),
  8
)

extract_chars_from_list <- function(item){
  for(item in my_list){
    if(is.character(item)){
      print(item)
    }
  }
}

extract_chars_from_list(my_list)
```

